'use client';

import { useEffect, useState } from 'react';

type Component={id:string;type:'Hero'|'Text'|'Image'|'Button'|'StaticHtml';props:Record<string,string>};
type Page={id:string;path:string;title:string;components:Component[]};
type Tree={pages:Page[]};
type Site={id:string;name:string;slug:string;draft_tree:Tree;draft_revision:number;published_version_id:string|null};
type Template={id:string;name:string;description:string};
type Version={id:string;version:number;created_at:string};
type Domain={id:string;hostname:string;status:string};

async function api<T>(path:string,method='GET',body?:unknown):Promise<T> {
  const response=await fetch(`/api/v1${path}`,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
  if (!response.ok) { const data=await response.json().catch(()=>({})); throw new Error(data.message??`Request failed (${response.status})`); }
  return response.json() as Promise<T>;
}
const uid=()=>Math.random().toString(36).slice(2,10);
const defaults:Record<Component['type'],Record<string,string>>={Hero:{heading:'Your headline',body:'Describe your business.',buttonText:'Get in touch',buttonHref:'#contact'},Text:{heading:'Section heading',body:'Add useful details.'},Image:{src:'https://placehold.co/800x400',alt:'Image description'},Button:{text:'Learn more',href:'#'},StaticHtml:{html:'<p>Imported HTML</p>'}};

export default function Websites() {
  const [sites,setSites]=useState<Site[]>([]); const [templates,setTemplates]=useState<Template[]>([]); const [site,setSite]=useState<Site|null>(null);
  const [tree,setTree]=useState<Tree|null>(null); const [pageIndex,setPageIndex]=useState(0); const [selected,setSelected]=useState<string|null>(null);
  const [name,setName]=useState(''); const [slug,setSlug]=useState(''); const [templateId,setTemplateId]=useState('');
  const [html,setHtml]=useState(''); const [prompt,setPrompt]=useState(''); const [hostname,setHostname]=useState('');
  const [versions,setVersions]=useState<Version[]>([]); const [domains,setDomains]=useState<Domain[]>([]);
  const [viewport,setViewport]=useState<'desktop'|'tablet'|'mobile'>('desktop'); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  async function refresh() { const [list,allTemplates]=await Promise.all([api<Site[]>('/websites'),api<Template[]>('/website-templates')]); setSites(list); setTemplates(allTemplates); if (!templateId && allTemplates[0]) setTemplateId(allTemplates[0].id); }
  async function open(id:string) { const [item,history,domainList]=await Promise.all([api<Site>(`/websites/${id}`),api<Version[]>(`/websites/${id}/versions`),api<Domain[]>(`/websites/${id}/domains`)]); setSite(item); setTree(item.draft_tree); setPageIndex(0); setSelected(null); setVersions(history); setDomains(domainList); }
  useEffect(()=>{ void Promise.all([api<Site[]>('/websites'),api<Template[]>('/website-templates')]).then(([list,allTemplates])=>{setSites(list);setTemplates(allTemplates);setTemplateId(allTemplates[0]?.id??'');}).catch((error)=>setMessage(error.message)); },[]);
  async function run(task:()=>Promise<void>) { setBusy(true); setMessage(''); try { await task(); } catch(error) { setMessage(error instanceof Error?error.message:'Action failed'); } finally { setBusy(false); } }
  function updateTree(change:(copy:Tree)=>void) { if (!tree) return; const copy=structuredClone(tree); change(copy); setTree(copy); }
  const page=tree?.pages[pageIndex]; const component=page?.components.find((item)=>item.id===selected);
  async function save() { if (!site||!tree) return; const result=await api<{draftRevision:number}>(`/websites/${site.id}/draft`,'PUT',{tree,expectedRevision:site.draft_revision}); setSite({...site,draft_revision:result.draftRevision,draft_tree:tree}); setMessage('Draft saved'); }
  function move(from:number,to:number) { if (from===to) return; updateTree((copy)=>{ const items=copy.pages[pageIndex].components; const [item]=items.splice(from,1); items.splice(to,0,item); }); }
  return <main className="wide builder">
    <p><a href="/">← Business OS</a></p><h1>Website builder</h1>
    {message&&<p role="alert">{message}</p>}
    <section className="builder-panel"><h2>Sites</h2><div className="builder-row">{sites.map((item)=><button key={item.id} onClick={()=>void run(()=>open(item.id))}>{item.name}</button>)}</div>
      <div className="builder-row"><input aria-label="New site name" placeholder="Site name" value={name} onChange={(e)=>setName(e.target.value)}/><input aria-label="New site slug" placeholder="unique-site-slug" value={slug} onChange={(e)=>setSlug(e.target.value)}/><select aria-label="Template" value={templateId} onChange={(e)=>setTemplateId(e.target.value)}>{templates.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={busy} onClick={()=>void run(async()=>{const created=await api<Site>('/websites','POST',{name,slug,templateId}); await refresh(); await open(created.id);})}>Create from template</button></div>
    </section>
    {site&&tree&&page&&<>
      <section className="builder-panel"><div className="builder-row"><h2>{site.name}</h2><span>Draft revision {site.draft_revision}</span><button disabled={busy} onClick={()=>void run(save)}>Save draft</button><button disabled={busy} onClick={()=>void run(async()=>{await save();await api(`/websites/${site.id}/publish`,'POST');await open(site.id);setMessage('Published');})}>Publish</button><button disabled={busy} onClick={()=>void run(async()=>{const copy=await api<Site>(`/websites/${site.id}/clone`,'POST',{name:`${site.name} copy`,slug:`${site.slug}-${uid()}`});await refresh();await open(copy.id);})}>Clone site</button><a href={`/api/v1/public/sites/${site.slug}`} target="_blank" rel="noreferrer">Open published site</a></div>
        <div className="builder-row"><label>Page <select value={pageIndex} onChange={(e)=>{setPageIndex(Number(e.target.value));setSelected(null);}}>{tree.pages.map((item,index)=><option key={item.id} value={index}>{item.title} ({item.path})</option>)}</select></label><button onClick={()=>updateTree((copy)=>{const id=`page-${uid()}`;copy.pages.push({id,path:`/${id}`,title:'New page',components:[]});setPageIndex(copy.pages.length-1);})}>Add page</button><input aria-label="Page title" value={page.title} onChange={(e)=>updateTree((copy)=>{copy.pages[pageIndex].title=e.target.value;})}/><input aria-label="Page path" value={page.path} onChange={(e)=>updateTree((copy)=>{copy.pages[pageIndex].path=e.target.value;})}/></div>
      </section>
      <div className="builder-layout"><section className="builder-panel"><h3>Page tree</h3><div className="builder-row"><select id="component-type" aria-label="Component type">{Object.keys(defaults).map((type)=><option key={type}>{type}</option>)}</select><button onClick={()=>{const type=(document.getElementById('component-type') as HTMLSelectElement).value as Component['type'];updateTree((copy)=>copy.pages[pageIndex].components.push({id:`block-${uid()}`,type,props:{...defaults[type]}}));}}>Add component</button></div>
          {page.components.map((item,index)=><button className={`builder-block ${selected===item.id?'active':''}`} key={item.id} draggable onDragStart={(event)=>event.dataTransfer.setData('text/plain',String(index))} onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{event.preventDefault();move(Number(event.dataTransfer.getData('text/plain')),index);}} onClick={()=>setSelected(item.id)}>{index+1}. {item.type} — {item.props.heading||item.props.text||item.props.alt||item.id}</button>)}
          {component&&<div><h3>Edit {component.type}</h3>{Object.entries(component.props).map(([key,value])=><label className="builder-field" key={key}>{key}{key==='body'||key==='html'?<textarea value={value} onChange={(e)=>updateTree((copy)=>{copy.pages[pageIndex].components.find((item)=>item.id===component.id)!.props[key]=e.target.value;})}/>:<input value={value} onChange={(e)=>updateTree((copy)=>{copy.pages[pageIndex].components.find((item)=>item.id===component.id)!.props[key]=e.target.value;})}/>}</label>)}<button onClick={()=>{updateTree((copy)=>{copy.pages[pageIndex].components=copy.pages[pageIndex].components.filter((item)=>item.id!==component.id);});setSelected(null);}}>Remove</button></div>}
        </section><section className="builder-panel"><div className="builder-row"><h3>Preview</h3>{(['desktop','tablet','mobile'] as const).map((size)=><button key={size} aria-pressed={viewport===size} onClick={()=>setViewport(size)}>{size}</button>)}</div><p>Save to refresh the server-rendered preview.</p><iframe title="Site preview" className={`site-preview ${viewport}`} src={`/api/v1/websites/${site.id}/preview?path=${encodeURIComponent(page.path)}&revision=${site.draft_revision}`}/></section></div>
      <div className="builder-layout"><section className="builder-panel"><h3>Import HTML</h3><p>Scripts and unsafe markup are removed. Complex layouts use a static fallback block.</p><textarea aria-label="HTML to import" value={html} onChange={(e)=>setHtml(e.target.value)} placeholder="Paste HTML here"/><button disabled={busy} onClick={()=>void run(async()=>{await api(`/websites/${site.id}/import-html`,'POST',{html,expectedRevision:site.draft_revision});await open(site.id);setMessage('HTML imported');})}>Import</button></section><section className="builder-panel"><h3>Generate with AI</h3><textarea aria-label="AI site prompt" value={prompt} onChange={(e)=>setPrompt(e.target.value)} placeholder="Describe your business and desired site"/><button disabled={busy} onClick={()=>void run(async()=>{await api(`/websites/${site.id}/generate`,'POST',{prompt,expectedRevision:site.draft_revision,idempotencyKey:uid()});await open(site.id);setMessage('AI draft generated');})}>Generate draft</button><p>Requires an AI entitlement, configured route, provider key, and monthly budget.</p></section></div>
      <div className="builder-layout"><section className="builder-panel"><h3>Versions</h3>{versions.map((item)=><div className="builder-row" key={item.id}>Version {item.version} <button disabled={busy} onClick={()=>void run(async()=>{await api(`/websites/${site.id}/rollback`,'POST',{versionId:item.id});await open(site.id);setMessage(`Rolled back to version ${item.version}`);})}>Rollback</button></div>)}</section><section className="builder-panel"><h3>Domains</h3>{domains.map((item)=><p key={item.id}>{item.hostname} — {item.status} {item.status==='PENDING_VERIFICATION'&&<button disabled={busy} onClick={()=>void run(async()=>{await api(`/website-domains/${item.id}/verify`,'POST');await open(site.id);})}>Verify DNS</button>}</p>)}<div className="builder-row"><input aria-label="Domain hostname" placeholder="www.example.com" value={hostname} onChange={(e)=>setHostname(e.target.value)}/><button disabled={busy} onClick={()=>void run(async()=>{const added=await api<{txtName:string;txtValue:string}>(`/websites/${site.id}/domains`,'POST',{hostname});await open(site.id);setMessage(`Add DNS TXT ${added.txtName} = ${added.txtValue}`);})}>Connect domain</button></div><p>DNS verification is followed by certificate provisioning and trusted edge activation.</p></section></div>
    </>}
  </main>;
}
